global:
    scrape_interval: 30s
    scrape_timeout: 10s
scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
         - targets: 
            - '13.233.250.246:9393'

